# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Julien Noé\OneDrive\0_Bureau\TP_CALCULATRICE\calcularice_ui.ui',
# licensing of 'C:\Users\Julien Noé\OneDrive\0_Bureau\TP_CALCULATRICE\calcularice_ui.ui' applies.
#
# Created: Wed Oct  9 10:03:04 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_form_calculatrice(object):
    def setupUi(self, form_calculatrice):
        form_calculatrice.setObjectName("form_calculatrice")
        form_calculatrice.resize(299, 480)
        form_calculatrice.setMinimumSize(QtCore.QSize(64, 64))
        form_calculatrice.setBaseSize(QtCore.QSize(64, 64))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        form_calculatrice.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(form_calculatrice)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.le_operation = QtWidgets.QLineEdit(form_calculatrice)
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(8)
        self.le_operation.setFont(font)
        self.le_operation.setFrame(False)
        self.le_operation.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_operation.setObjectName("le_operation")
        self.gridLayout.addWidget(self.le_operation, 0, 0, 1, 4)
        self.le_resultat = QtWidgets.QLineEdit(form_calculatrice)
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.le_resultat.setFont(font)
        self.le_resultat.setFrame(False)
        self.le_resultat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_resultat.setObjectName("le_resultat")
        self.gridLayout.addWidget(self.le_resultat, 1, 0, 1, 4)
        self.btn_c = QtWidgets.QPushButton(form_calculatrice)
        self.btn_c.setMinimumSize(QtCore.QSize(64, 64))
        self.btn_c.setMaximumSize(QtCore.QSize(64, 64))
        self.btn_c.setFlat(True)
        self.btn_c.setObjectName("btn_c")
        self.gridLayout.addWidget(self.btn_c, 2, 0, 1, 1)
        self.btn_slash = QtWidgets.QPushButton(form_calculatrice)
        self.btn_slash.setMinimumSize(QtCore.QSize(64, 64))
        self.btn_slash.setMaximumSize(QtCore.QSize(64, 64))
        self.btn_slash.setFlat(True)
        self.btn_slash.setObjectName("btn_slash")
        self.gridLayout.addWidget(self.btn_slash, 2, 3, 1, 1)
        self.btn_7 = QtWidgets.QPushButton(form_calculatrice)
        self.btn_7.setMinimumSize(QtCore.QSize(64, 64))
        self.btn_7.setMaximumSize(QtCore.QSize(64, 64))
        self.btn_7.setBaseSize(QtCore.QSize(64, 64))
        self.btn_7.setFlat(True)
        self.btn_7.setObjectName("btn_7")
        self.gridLayout.addWidget(self.btn_7, 3, 0, 1, 1)
        self.btn_8 = QtWidgets.QPushButton(form_calculatrice)
        self.btn_8.setMinimumSize(QtCore.QSize(64, 64))
        self.btn_8.setMaximumSize(QtCore.QSize(64, 64))
        self.btn_8.setBaseSize(QtCore.QSize(64, 64))
        self.btn_8.setFlat(True)
        self.btn_8.setObjectName("btn_8")
        self.gridLayout.addWidget(self.btn_8, 3, 1, 1, 1)
        self.btn_9 = QtWidgets.QPushButton(form_calculatrice)
        self.btn_9.setMinimumSize(QtCore.QSize(64, 64))
        self.btn_9.setMaximumSize(QtCore.QSize(64, 64))
        self.btn_9.setFlat(True)
        self.btn_9.setObjectName("btn_9")
        self.gridLayout.addWidget(self.btn_9, 3, 2, 1, 1)
        self.btn_x = QtWidgets.QPushButton(form_calculatrice)
        self.btn_x.setMinimumSize(QtCore.QSize(64, 64))
        self.btn_x.setMaximumSize(QtCore.QSize(64, 64))
        self.btn_x.setFlat(True)
        self.btn_x.setObjectName("btn_x")
        self.gridLayout.addWidget(self.btn_x, 3, 3, 1, 1)
        self.btn_4 = QtWidgets.QPushButton(form_calculatrice)
        self.btn_4.setMinimumSize(QtCore.QSize(64, 64))
        self.btn_4.setMaximumSize(QtCore.QSize(64, 64))
        self.btn_4.setFlat(True)
        self.btn_4.setObjectName("btn_4")
        self.gridLayout.addWidget(self.btn_4, 4, 0, 1, 1)
        self.btn_5 = QtWidgets.QPushButton(form_calculatrice)
        self.btn_5.setMinimumSize(QtCore.QSize(64, 64))
        self.btn_5.setMaximumSize(QtCore.QSize(64, 64))
        self.btn_5.setFlat(True)
        self.btn_5.setObjectName("btn_5")
        self.gridLayout.addWidget(self.btn_5, 4, 1, 1, 1)
        self.btn_6 = QtWidgets.QPushButton(form_calculatrice)
        self.btn_6.setMinimumSize(QtCore.QSize(64, 64))
        self.btn_6.setMaximumSize(QtCore.QSize(64, 64))
        self.btn_6.setFlat(True)
        self.btn_6.setObjectName("btn_6")
        self.gridLayout.addWidget(self.btn_6, 4, 2, 1, 1)
        self.btn_neg = QtWidgets.QPushButton(form_calculatrice)
        self.btn_neg.setMinimumSize(QtCore.QSize(64, 64))
        self.btn_neg.setMaximumSize(QtCore.QSize(64, 64))
        self.btn_neg.setFlat(True)
        self.btn_neg.setObjectName("btn_neg")
        self.gridLayout.addWidget(self.btn_neg, 4, 3, 1, 1)
        self.btn_1 = QtWidgets.QPushButton(form_calculatrice)
        self.btn_1.setMinimumSize(QtCore.QSize(64, 64))
        self.btn_1.setMaximumSize(QtCore.QSize(64, 64))
        self.btn_1.setFlat(True)
        self.btn_1.setObjectName("btn_1")
        self.gridLayout.addWidget(self.btn_1, 5, 0, 1, 1)
        self.btn_2 = QtWidgets.QPushButton(form_calculatrice)
        self.btn_2.setMinimumSize(QtCore.QSize(64, 64))
        self.btn_2.setMaximumSize(QtCore.QSize(64, 64))
        self.btn_2.setFlat(True)
        self.btn_2.setObjectName("btn_2")
        self.gridLayout.addWidget(self.btn_2, 5, 1, 1, 1)
        self.btn_3 = QtWidgets.QPushButton(form_calculatrice)
        self.btn_3.setMinimumSize(QtCore.QSize(64, 64))
        self.btn_3.setMaximumSize(QtCore.QSize(64, 64))
        self.btn_3.setFlat(True)
        self.btn_3.setObjectName("btn_3")
        self.gridLayout.addWidget(self.btn_3, 5, 2, 1, 1)
        self.btn_add = QtWidgets.QPushButton(form_calculatrice)
        self.btn_add.setMinimumSize(QtCore.QSize(64, 64))
        self.btn_add.setMaximumSize(QtCore.QSize(64, 64))
        self.btn_add.setFlat(True)
        self.btn_add.setObjectName("btn_add")
        self.gridLayout.addWidget(self.btn_add, 5, 3, 1, 1)
        self.btn_0 = QtWidgets.QPushButton(form_calculatrice)
        self.btn_0.setMinimumSize(QtCore.QSize(64, 64))
        self.btn_0.setMaximumSize(QtCore.QSize(64, 64))
        self.btn_0.setFlat(True)
        self.btn_0.setObjectName("btn_0")
        self.gridLayout.addWidget(self.btn_0, 6, 1, 1, 1)
        self.btn_point = QtWidgets.QPushButton(form_calculatrice)
        self.btn_point.setMinimumSize(QtCore.QSize(64, 64))
        self.btn_point.setMaximumSize(QtCore.QSize(64, 64))
        self.btn_point.setFlat(True)
        self.btn_point.setObjectName("btn_point")
        self.gridLayout.addWidget(self.btn_point, 6, 2, 1, 1)
        self.btn_equal = QtWidgets.QPushButton(form_calculatrice)
        self.btn_equal.setMinimumSize(QtCore.QSize(64, 64))
        self.btn_equal.setMaximumSize(QtCore.QSize(64, 64))
        self.btn_equal.setFlat(True)
        self.btn_equal.setObjectName("btn_equal")
        self.gridLayout.addWidget(self.btn_equal, 6, 3, 1, 1)

        self.retranslateUi(form_calculatrice)
        QtCore.QMetaObject.connectSlotsByName(form_calculatrice)

    def retranslateUi(self, form_calculatrice):
        form_calculatrice.setWindowTitle(QtWidgets.QApplication.translate("form_calculatrice", "Ma Calculatrice", None, -1))
        self.le_operation.setText(QtWidgets.QApplication.translate("form_calculatrice", "0", None, -1))
        self.le_resultat.setText(QtWidgets.QApplication.translate("form_calculatrice", "0", None, -1))
        self.btn_c.setText(QtWidgets.QApplication.translate("form_calculatrice", "c", None, -1))
        self.btn_slash.setText(QtWidgets.QApplication.translate("form_calculatrice", "/", None, -1))
        self.btn_7.setText(QtWidgets.QApplication.translate("form_calculatrice", "7", None, -1))
        self.btn_8.setText(QtWidgets.QApplication.translate("form_calculatrice", "8", None, -1))
        self.btn_9.setText(QtWidgets.QApplication.translate("form_calculatrice", "9", None, -1))
        self.btn_x.setText(QtWidgets.QApplication.translate("form_calculatrice", "X", None, -1))
        self.btn_4.setText(QtWidgets.QApplication.translate("form_calculatrice", "4", None, -1))
        self.btn_5.setText(QtWidgets.QApplication.translate("form_calculatrice", "5", None, -1))
        self.btn_6.setText(QtWidgets.QApplication.translate("form_calculatrice", "6", None, -1))
        self.btn_neg.setText(QtWidgets.QApplication.translate("form_calculatrice", "-", None, -1))
        self.btn_1.setText(QtWidgets.QApplication.translate("form_calculatrice", "1", None, -1))
        self.btn_2.setText(QtWidgets.QApplication.translate("form_calculatrice", "2", None, -1))
        self.btn_3.setText(QtWidgets.QApplication.translate("form_calculatrice", "3", None, -1))
        self.btn_add.setText(QtWidgets.QApplication.translate("form_calculatrice", "+", None, -1))
        self.btn_0.setText(QtWidgets.QApplication.translate("form_calculatrice", "0", None, -1))
        self.btn_point.setText(QtWidgets.QApplication.translate("form_calculatrice", ".", None, -1))
        self.btn_equal.setText(QtWidgets.QApplication.translate("form_calculatrice", "=", None, -1))

